### ISSUE TITLE
Error in production build working fine in ng build but when i do ng build --prod give me below error.

### ISSUE THREAD

**Issue by hamzash750** [abadakhshan/narik-angular-color-picker#1]
ERROR in : Couldn't resolve resource ./templates/default/color-picker.scss relative to D:/iot-portal/node_modules/narik-angular-color-picker/dist/esm/src/color-picker.directive.d.ts

**Comment by Percipient24** [comment]
We're having the same issue over here... looking into potential fixes. 🤞

**Comment by Percipient24** [comment]
We migrated to ngx-color-picker : https://github.com/zefoy/ngx-color-picker (no offense).

**Comment by abadakhshan** [comment]
Hello

The problem was fixed and deployed on npm

Please use narik-angular-color-picker@2.0.9

**Comment by Percipient24** [comment]
Thank you!
